consul_version: "1.4.0"

directories:
  - /etc/consul.d
  - /data/consul
  - /data/consul/logs
  - /data/consul/scripts
  - /data/consul/config

files: 
  - { src: "consul-template", dest: "/usr/local/bin/consul-template", mode: "0755" }
  - { src: "ui", dest: "/data/consul", mode: "0744" }
  - { src: "mem.sh", dest: "/data/consul/scripts/mem.sh", mode: "0755" }
  - { src: "disk.sh", dest: "/data/consul/scripts/disk.sh", mode: "0755" }
  - { src: "jq", dest: "/usr/local/bin/jq", mode: "0755" }

upstartfiles:
  - { src: "consul.conf", dest: "/etc/init/consul.conf", mode: "0644" }

systemdunits:
  - { src: "consul.service", dest: "/lib/systemd/system/consul.service", mode: "0644" }
  - { src: "registrator.service", dest: "/lib/systemd/system/registrator.service", mode: "0644" }
  - { src: "registrator-kv.service", dest: "/lib/systemd/system/registrator-kv.service", mode: "0644" }

templates: 
  - { src: "redeploy_service.sh.j2", dest: "/data/consul/scripts/redeploy_service.sh", mode: "0755" }
  - { src: "start-consul.sh.j2", dest: "/usr/local/bin/start-consul.sh", mode: "0755" }
  - { src: "start-registrator.sh.j2", dest: "/usr/local/bin/start-registrator.sh", mode: "0755" }
  - { src: "start-registrator-kv.sh.j2", dest: "/usr/local/bin/start-registrator-kv.sh", mode: "0755" }

